feat(utils): implement a new design for stdout
code-pushup/cli pull request #206
Opened 2023-11-06 21:49 UTC by IKatsuba

Closes #190

2023-11-07 10:16 UTC, matejchalk requested changes
I tested it out for our example app (`npx nx run cli:run-collect`), added a few visual notes. I'm not sure why the bold formatting isn't working properly in the audits section, since the code is the same as my PoC :confused: 

I got the feeling `cliui` was quite buggy in this, so maybe we could also consider some alternative package (maybe [table-layout](https://www.npmjs.com/package/table-layout)?) or even write it ourselves (all we need is the column alignment and word wrapping).

![image](https://github.com/flowup/quality-metrics-cli/assets/34691111/5e0cf5da-80c2-4235-b7a4-9bff71f3c7a4)

2023-11-09 00:31 UTC, IKatsuba commented
> I tested it out for our example app (`npx nx run cli:run-collect`) and added a few visual notes. I'm not sure why the bold formatting isn't working correctly in the audits section since the code is the same as my PoC 😕
> 
> I got the feeling `cloud` was quite buggy in this, so maybe we could also consider some alternative package (maybe [table-layout](https://www.npmjs.com/package/table-layout)?) or even write it ourselves (all we need is the column alignment and word wrapping).

All CLI packages do strange things. I left the current packages but rendered the full report one time.

Do not use `nx run-collect` if you want to test it. It removes new line symbols with no reason. Just run 
```
npx ../../dist/packages/cli collect --persist.format=stdout --persist.format=stdout
```
in `examples/react-todos-app.`

2023-11-09 10:58 UTC, Tlacenka reviewed
I ran it on Windows in VSCode with light theme. Looking good! 🌈 

## In-scope comment
- While a preceding empty line is nice for the section, it should visually belong to the text below so I wouldn't put a new line right after it. In the original design, the preceding line is bigger than the gap after the title as well.

## OOS
- Is there any way of wrapping words to a new line so that they aren't cut off like that?
   - To be continued in #209 
- The footer line is missing a whitespace (has been ever since I joined) and I would really like to see that fixed. → Won't fix atm.
- This is a suggestion for both MD and stdout - can we sort the output e.g. based on number of errros, then warnings? The user now has to skim through it seemingly with no logical ordering.
   - To be continued in #210 

![image](https://github.com/flowup/quality-metrics-cli/assets/6306671/31dfeb68-105f-4f17-949c-04cf5e469a75)

2023-11-09 10:58 UTC, matejchalk approved these changes
Thanks for the fixes, the output looks really good now :+1: 

I have suggestions regarding code style. But the functionality itself is now working as I would expect and the sanitized snapshot is now much more easy to understand as well.

2023-11-09 11:43 UTC, matejchalk commented
@Tlacenka While I agree with your comments, I think changes to the original design should handled as another issue, so we don't bloat this PR. These changes are already a big improvement over the formatting we have in `main`, in my opinion.

> Is there any way of wrapping words to a new line so that they aren't cut off like that?

Yes, that bugs me as well :grimacing: 

Unfortunately, it looks like `cliui` doesn't handle it properly because of some complicated ESM vs CJS stuff, I came across [this issue](https://github.com/yargs/cliui/issues/89). So we may have to switch libraries or implement the inteligent word wrapping ourselves.

But I do agree it would improve the output a lot, many of the audit titles won't fit on one line, so it's not really an edge case.

> The footer line is missing a whitespace (has been ever since I joined) and I would really like to see that fixed.

This is a weird one. The space is actually there, it's just that some terminals don't render it after the heart. E.g. my VSCode integrated terminal renders it, but my regular Linux terminal doesn't (same as your Windows terminal) :confused: 

> This is a suggestion for both MD and stdout - can we sort the output e.g. based on number of errros, then warnings? The user now has to skim through it seemingly with no logical ordering.

Yes, I can see that would be useful. Could you create a separate issue for that? I'm not sure what the best ordering would be (could be weight, score, alphabetical :man_shrugging:), that's something we can discuss during refinement.

> While a preceding empty line is nice for the section, it should visually belong to the text below so I wouldn't put a new line right after it. In the original design, the preceding line is bigger than the gap after the title as well.

Good catch :+1:  In my PoC, I put an extra blank line before the title (so it's 2 blank lines before and 1 after). That would be an easy improvement, I believe.

2023-11-09 20:57 UTC, IKatsuba commented on packages/utils/src/lib/report-to-stdout.ts
>  export function reportToStdout(report: ScoredReport): void {
I love this idea! Thank you!

2023-11-09 21:38 UTC, IKatsuba commented
I added the extra line before the titles. I agree; this is more readable.

Did small refactoring. `reportToStdout` now returns `string`.

About whitespace after ❤️. I tried to change to another symbol. 
<img width="327" alt="image" src="https://github.com/flowup/quality-metrics-cli/assets/10637135/7f868ee4-4166-4d52-a3c1-7e333ad7dd5b">

@Tlacenka, could you check it out?

2023-11-10 09:29 UTC, matejchalk commented
> About whitespace after ❤️. I tried to change to another symbol.

For me that did the trick :+1: 

![image](https://github.com/flowup/quality-metrics-cli/assets/34691111/bd1883d3-38b6-40ce-ae83-505fea70c52e)

Before it rendered like this:

![image](https://github.com/flowup/quality-metrics-cli/assets/34691111/88915802-62f7-441d-81f4-1c88520db1fb)

2023-11-10 09:46 UTC, Tlacenka submitted a review, later dismissed
All defined acceptance criteria is met based on the original design now. 💯 

The preceding gap for a section title is now bigger. ✔️ 

Unfortunately, the heart emoji still does not render a whitespace after it. It is now a different emoji than before (black and white) but the space is still missing. 😢 

![image](https://github.com/flowup/quality-metrics-cli/assets/6306671/cc16a47e-0f71-4582-b845-2aef933da966)

2023-11-13 20:27 UTC, matejchalk submitted a review, later dismissed

2023-11-13 20:31 UTC, BioPhoton commented on packages/core/src/lib/implementation/persist.spec.ts
> +    expect(logs.join('\n')).toContain(`${FOOTER_PREFIX} ${CODE_PUSHUP_DOMAIN}`);
Can we use the const `NEW_LINE` here please

2023-11-13 20:31 UTC, BioPhoton commented on packages/core/src/lib/implementation/persist.spec.ts
> +    expect(logs.join('\n')).toMatch(`${FOOTER_PREFIX} ${CODE_PUSHUP_DOMAIN}`);
same as above, use the `NEW_LINE` constant please

2023-11-13 20:32 UTC, BioPhoton commented on packages/utils/src/lib/report-to-stdout.spec.ts
> +    expect(logOutput.replace(/\u001B\[\d+m/g, '')).toMatchSnapshot();
please add a comment what ´/\u001B\[\d+m/g´ is doing 🙏

2023-11-13 21:00 UTC, BioPhoton approved these changes
<3

2023-11-13 21:02 UTC, merged