build: migrate to Nx v17 inc deps
code-pushup/cli pull request #252
Opened 2023-11-14 15:50 UTC by BioPhoton

2023-11-14 18:23 UTC, BioPhoton commented
I don't really get why the eslint-plugin tests fail... @vmasek any clue?

2023-11-14 22:53 UTC, BioPhoton commented
I know now why the tests where failing. They rely on real eslint setup and the ouatput data changed.
@matejchalk I already created #255 and #254 and updated #224 

What would be the minimum fix to make this PR turn 🟢?

2023-11-15 13:27 UTC, BioPhoton commented
I wanted to get the update in before, but also decided to day that its not a good idea.

2023-11-19 17:43 UTC, BioPhoton commented
Ok, I gave the test refactoring a try based on our discussions with @Tlacenka. It's not perfect but much more entangles and smaller in rules. 

@matejchalk let me know if I can polish this version or if I can adopt it.

2023-11-21 13:11 UTC, matejchalk requested changes
Sorry, but the PR scope is too big. Refactoring the `plugin-eslint` tests isn't necessary to update Nx. Please revert those changes and just run `npx nx test plugin-eslint -u` to update the snapshot.

The fact that the tests failed after a major update isn't a bad thing, in my opinion. It gives us visibility into the impact of those changes.

2023-11-22 15:39 UTC, BioPhoton commented on nx.json
>      },
that was done by the Nx migration. They changed the targets and caching definition. Both changes are in `nx.json`.

I had no time to merge that with @Tlacenka's changes so far

2023-11-22 15:40 UTC, BioPhoton commented
@matejchalk 
I will first refactor the plugin-eslint tests and then update.

2023-11-22 15:42 UTC, BioPhoton commented on migrations.json
Yes! Also documented here:
https://nx.dev/core-features/automate-updating-dependencies#step-3-cleaning-up

2023-11-22 15:42 UTC, BioPhoton commented on migrations.json
Just learned that it is not needed anymore

2023-11-22 15:54 UTC, matejchalk commented
> I will first refactor the plugin-eslint tests and then update Nx.

But why? :sweat_smile: The priorities are completely the opposite in my opinion. I'm not even convinced the ESLint tests need to be refactored (would be good to get @Tlacenka's opinion on this), and it surely isn't a blocker for updating Nx (`npx nx test plugin-eslint -u` is the only necessary step, I believe).

I honestly don't like having to decline your PRs, but when you decide to make big chances before first consulting it with us (e.g. on refinement), then I'm afraid it's gonna keep happening :disappointed:

2023-11-22 17:02 UTC, Tlacenka commented
> I'm not even convinced the ESLint tests need to be refactored (would be good to get @Tlacenka's opinion on this)

The `plugin-eslint` package in the original version is in my opinion sufficiently covered  by both unit (internal logic) and integration (initiation and executing the runner) tests.

I am unfortunately unable to determine which changes are truly necessary due to the updated `nx` version. The ESLint rules and results seem to be different, variables renamed.

Should the changes be done as a part of #255 , they should in my opinion be first investigated in detail and any targetted changes should be scoped and prioritised separately (otherwise the issue could get bloated easily), not as a part of this PR.

2023-11-27 01:57 UTC, closed without merging