feat(utils): add file-system helper
code-pushup/cli pull request #336
Opened 2023-11-29 15:40 UTC by BioPhoton

This PR is a result of the plugin docs and examples we are working on.
The added helper will reduce the code drastically in both docs and example code.

This PR includes:
- merging files and tests
- add 2 helper to `file-system.ts`
- introduce `formatting.ts`

2023-11-29 17:03 UTC, matejchalk requested changes

2023-11-29 17:03 UTC, matejchalk commented on packages/utils/src/lib/file-system.ts
> +    fileTransform = (filePath: string) => filePath as unknown as T,
Can be simplified:

```suggestion
    fileTransform = (filePath: string) => filePath as T,
```

2023-11-29 17:03 UTC, matejchalk commented on packages/utils/src/lib/file-system.unit.test.ts
> +describe('findLineNumber', () => {
```suggestion
describe('findLineNumberInText', () => {
```

2023-11-30 11:01 UTC, BioPhoton commented on packages/utils/src/lib/transformation.ts
> +  filterCount = Math.max(filterCount, 0);
Thx for the catch!!

2023-11-30 11:02 UTC, BioPhoton commented on packages/utils/src/lib/transformation.ts
> +  return filterCount > 0 ? Math.abs((itemCount - filterCount) / itemCount) : 1;
yes. leftover from the refactoring i gess

2023-11-30 11:12 UTC, matejchalk commented on packages/utils/src/lib/file-system.ts
> +    }
Bit of a nitpick, but when you `return` in the `if`-block you don't need the `else` branch - helps flatten the code a bit.

```suggestion
    if (stats.isDirectory()) {
      return crawlFileSystem({ directory: filePath, pattern, fileTransform });
    }
    if (stats.isFile() && (!pattern || new RegExp(pattern).test(file))) {
      return fileTransform(filePath);
    }
    return [];
```

2023-11-30 18:35 UTC, matejchalk approved these changes

2023-11-30 18:45 UTC, merged