feat(cli): implement `merge-diffs` command
code-pushup/cli pull request #800
Opened 2024-08-16 16:50 UTC by matejchalk

Part of #731 (CLI)

New `merge-diffs` command implemented, which parses list of `report-diff.json` paths from required `--files` option and uses Markdown formatter from #793 to generate single `report-diff.md`.

Also added a `--label` option to `compare` command, which can be used to set project names for the JSON diffs (parent directory used as fallback).

2024-08-18 20:17 UTC, BioPhoton commented on packages/core/src/lib/merge-diffs.ts
> +      const diff = await reportsDiffSchema.parseAsync(json);
I suggest adding using parseSafe to be able to add a better readable error message.

It would already help to tell the user that the error occurred because the content of the file xyz did not contain a valid report diff or similar. In the future I will ship a helper function to turn the Error into a readable text. PoC already exists.

2024-08-18 20:20 UTC, BioPhoton requested changes
Nice to have a command for it and not just loose scripts!
Left comments for a slight adoption of the docs.

2024-08-19 11:59 UTC, matejchalk commented on e2e/cli-e2e/tests/__snapshots__/help.e2e.test.ts.snap
> +  code-pushup merge-diffs   Combine many report diffs into single report-diff.md
Updated description.

2024-08-19 12:00 UTC, matejchalk commented on packages/core/src/lib/merge-diffs.ts
> +      const diff = await reportsDiffSchema.parseAsync(json);
Agreed, improved the error messages :heavy_check_mark: Added a basic helper function in `utils` which could serve as a good basis for safely formatting error messages.

2024-08-19 12:25 UTC, merged