feat: add keywords for NPM to display
code-pushup/cli pull request #846
Opened 2024-10-16 08:20 UTC by vmasek

NPM displays keywords and uses them for search categorizing, I've added a few so our package is more visible

2024-10-16 08:33 UTC, matejchalk requested changes

2024-10-16 08:52 UTC, vmasek commented on package.json
> +  "keywords": [
Thanks, I suspected I need to copy it to individual ones, will do.

2024-10-16 16:10 UTC, vmasek commented on packages/nx-plugin/package.json
> +    "url": "https://github.com/code-pushup/cli/issues?q=is%3Aissue%20state%3Aopen%20type%3ABug%20label%3A\"🧩%20nx-plugin\""
I went ahead and marked all open & closed issues with the `Bug` type and I checked it displays correctly even in a private tab so I'd say it should be good. I can have a look if the templates support it now and if no we anyway need to acknowledge these bugs in the processing column

2024-10-16 16:25 UTC, vmasek commented on packages/plugin-coverage/package.json
> +    "url": "https://github.com/code-pushup/cli/issues?q=is%3Aissue%20state%3Aopen%20type%3ABug"
done

2024-10-17 08:23 UTC, matejchalk commented on packages/nx-plugin/package.json
> +    "url": "https://github.com/code-pushup/cli/issues?q=is%3Aissue%20state%3Aopen%20type%3ABug%20label%3A\"🧩%20\""
```suggestion
    "url": "https://github.com/code-pushup/cli/issues?q=is%3Aissue%20state%3Aopen%20type%3ABug%20label%3A\"🧩%20nx-plugin\""
```

2024-10-17 13:55 UTC, matejchalk approved these changes

2024-10-17 13:55 UTC, merged