test(plugin-js-packages-e2e): create vulnerabilities e2e test
code-pushup/cli pull request #898
Opened 2024-12-21 01:12 UTC by vmasek

2025-01-06 11:40 UTC, matejchalk requested changes

2025-01-06 11:40 UTC, matejchalk commented on e2e/plugin-js-packages-e2e/tests/plugin-js-packages.e2e.test.ts
> +              value: expect.closeTo(7, 10), // there are 7 vulnerabilities (6 high, 1 low) at the time
This will fail as soon as a new vulnerability is reported. Using `expect.closeTo` doesn't solve anything here, because the values are integers, so the difference won't be less than 10 decimals.

A more future proof assertion would be something like `expect(audit.value).toBeGreaterThanOrEqual(7)`, but that doesn't have an inline variant, so you'll need to break this up into multiple assertions.

2025-01-06 11:40 UTC, matejchalk commented on e2e/plugin-js-packages-e2e/mocks/fixtures/npm-repo/code-pushup.config.ts
> +  ],
I don't think the categories need to be included here. The test only asserts the slugs are in the resulting report, but that's not the responsibility of this plugin.

2025-01-06 11:40 UTC, matejchalk commented on e2e/plugin-js-packages-e2e/tests/plugin-js-packages.e2e.test.ts
> +                issues: expect.any(Array),
How about checking for one of the expected vulnerabilities?

```suggestion
                issues: expect.arrayContaining([
                  {
                    "message": "`express`'s dependency `connect` has a **high** vulnerability in versions **<=2.30.2**. Fix available: Update `express` to version **4.21.2** (breaking change). More information: [methodOverride Middleware Reflected Cross-Site Scripting in connect](https://github.com/advisories/GHSA-3fw8-66wf-pr7m)",
                    "severity": "error"
                  },
                ]),
```

Might require a regex for the message though, since the suggested `4.21.2` update is probably just the latest `express` version :thinking:

2025-01-06 11:40 UTC, matejchalk commented on e2e/plugin-js-packages-e2e/tests/plugin-js-packages.e2e.test.ts
> +                      /Package \[`express`].*\*\*major\*\* update from \*\*\d+\.\d+\.\d+\*\* to \*\*\d+\.\d+\.\d+\*\*/,
Only the new version will change over time, otherwise you could check the full message :thinking: 

```suggestion
                      /^Package \[`express`]\(http:\/\/expressjs\.com\) requires a \*\*major\*\* update from \*\*3.0.0\*\* to \*\*\d+\.\d+\.\d+\*\*\.$/,
```

2025-01-06 11:40 UTC, matejchalk commented on e2e/plugin-js-packages-e2e/tests/plugin-js-packages.e2e.test.ts
> +                ]),
Since there aren't any other issues or issue fields than the ones you mention, you can omit the `expect.arrayContaining` and `expect.objectContaining` wrappers.

```suggestion
                issues: [
                  {
                    message: expect.stringMatching(
                      /Package \[`express`].*\*\*major\*\* update from \*\*\d+\.\d+\.\d+\*\* to \*\*\d+\.\d+\.\d+\*\*/,
                    ),
                    severity: 'error',
                  },
                ],
```

2025-01-06 11:40 UTC, matejchalk commented on e2e/plugin-js-packages-e2e/tests/plugin-js-packages.e2e.test.ts
> +    expect.objectContaining({
Umm ... this doesn't assert anything :sweat_smile: Assymetrics matchers like `expect.objectContaining` need to be used with `expect(...).toEqual(...)` or `expect(...).toHaveBeenCalledWith(...)`. On their own they don't do anything - how could they, when the value (in this case `report`) isn't being specified anywhere.

The assertion would need to be:

```ts
expect(report).toEqual(expect.objectContaining<Partial<Report>>({
  // ...
}));
```

(BTW without adding a type parameter, everything in the matcher is typed as `any`.)

However, you may need to break this into multiple assertions - see my other comment about replacing `expect.closeTo(7)` with `expect(...).toBeGreaterThan(7)`. So it'll probably be something along these lines in the end:

```ts
const plugin = report.plugins[0]!;
expect(plugin.packageName).toBe('@code-pushup/js-packages-plugin');
expect(plugin.audits).toHaveLength(2);
expect(plugin.audits[0]).toEqual<AuditReport>({
  // ...
  value: expect.any(Number),
}));
expect(plugin.audits[0]!.value).toBeGreaterThan(7);
expect(plugin.audits[1]).toEqual<AuditReport>({
  // ...
}));
```

2025-01-06 11:40 UTC, matejchalk commented on e2e/plugin-js-packages-e2e/tests/plugin-js-packages.e2e.test.ts
> +    expect(installCode).toBe(0);
Since neither `npm audit` or `npm outdated` rely on packages actually being installed in `node_modules`, I'm guessing running `npm install` only serve to create the `package-lock.json`? It would be more optimal to just commit the `package-lock.json` in the test fixture, that we way we don't have to run `npm install` and the test will be faster.

2025-01-06 12:12 UTC, matejchalk commented on e2e/plugin-js-packages-e2e/tests/plugin-js-packages.e2e.test.ts
> +  omitVariableReportData,
This is unused.

2025-01-06 12:59 UTC, vmasek commented on e2e/plugin-js-packages-e2e/tests/plugin-js-packages.e2e.test.ts
> +              value: expect.closeTo(7, 10), // there are 7 vulnerabilities (6 high, 1 low) at the time
I uderstood the assertion purpose differently, thanks dor explanation

2025-04-01 10:53 UTC, matejchalk commented on packages/plugin-js-packages/src/lib/config.unit.test.ts
> -  });
I don't see why we shouldn't keep this test. Why not just adjust `packageJsonPath`?

2025-04-01 11:36 UTC, vmasek commented on packages/plugin-js-packages/src/lib/config.unit.test.ts
> -  });
We can, I deleted it as it felt too similar to the one bellow, but this one uses just `prod` and different package manager, I'll add it back

2025-04-01 13:53 UTC, merged